name: Solvia Alert Bot

on:
  schedule:
    # Corre cada 30 minutos, puedes ajustar el cron
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # instala aquí lo que necesites, por ejemplo requests
        pip install requests

    - name: Run solvia_bot.py
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python solvia_bot.py

    - name: Configurar git para push con PAT
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/alexvazvi/solviaalertbot.git

    - name: Commit y push cambios
      run: |
        git add pisos_guardados.json
        git commit -m "Update pisos_guardados.json" || echo "No changes"
        git push origin main
