name: Solvia Bot

on:
  schedule:
    - cron: "*/10 * * * *" # cada 10 minutos
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List files in repo
        run: ls -R

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run Solvia bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python solvia_bot.py

      - name: Configure git for push with PAT
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/alexvazvi/solviaalertbot.git

      - name: Commit pisos_guardados.json
        run: |
          git add pisos_guardados.json
          git commit -m "Update pisos_guardados.json" || echo "No changes"
          git push origin main